---

db:
  postgress_auth: {"db": Cargamos_Inventory, "usr": POSTGRES_USER, "pwd": "POSTGRES_PWD", "port": 5432, "host": "localhost"}

queries:
  add_shop: INSERT INTO shops (id, {})
            VALUES ((SELECT MAX(id)+1 FROM shops), %s, %s,%s, %s ,%s, %s, %s, %s);
  
  add_product: INSERT INTO products_el (id, {})
               VALUES ((SELECT MAX(id)+1 FROM products_el), %s,%s, %s,%s, %s ,%s, %s, %s, %s, %s);
  test: SELECT * FROM products_el;
  get_shop: SELECT name, address, city, country,state, phone, schedule, warehouse FROM shops WHERE name = '{}';
  get_shops: SELECT name, address, city, country,state, phone, schedule, warehouse FROM shops;
  get_product: SELECT brand, class, color, extra, model, sku, status, type, shop, warehouse FROM products_el WHERE sku = '{}'
  get_shop_warehosue: SELECT name, address, city, country,state, phone, schedule, warehouse FROM shops WHERE warehouse = '{}' AND name = '{}';

definition_type:
  product_class:
    - EL  #ELECTRONIC
    - SP  #SPORTS
    - FT  #FOOTWEAR
  product_tags: {"PHONE":"PHN", "TV":"TV", "HEADPHONES":"HDPS", "SNIKERS":"SNK", "BOOTS":"BTS"}
  brand_tags: {"SAMMSUNG": "SMS", "HUAWEI":"HWI", "ASUS":"AS", "NIKE":"NK", "ADIDAS": "ADS", "CATERPILLAR":"CTPLL"}